### PR TITLE
Rewrite scraper to get applications from new page

### PR DESCRIPTION
**Pull request by CloCkWeRX**
http://www.sorell.tas.gov.au/publications/currently-advertised-applications/ is the new home for a bunch of PDFs.

Unfortunately, I can't get a description from the pdf even with PDF reader due to things like 

```
/home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/pdf-reader-1.3.3/lib/pdf/reader/filter/flate.rb:34:in `rescue in filter': Error occured while inflating a compressed stream (Zlib::DataError: invalid code lengths set) (PDF::Reader::MalformedPDFError)
```

### CODE REVIEW

**Comment by henare** [comment]
Nasty! I think you've made the best of a bad situation with this though :+1: 

There's a couple of issues with the address:
- [x] Address contains non-address data, `Re-Advertised`
- [x] Add state to address to increase likelihood of accurate geocoding

selection_001

**Comment by CloCkWeRX** [comment]
This one seems ready - test data @ https://morph.io/CloCkWeRX/sorell

**Comment by henare** [comment]
Sorry it's taken me a while to look at this. It looks like another exception has cropped up - what a pain:

selection_001

Do you think you can add a fix for that @CloCkWeRX?

**Comment by CloCkWeRX** [comment]
It appears to be human error:

```
DA2016.58 -17 (Lot 35) Barilla Court, Midway Point - Representations Close Thursday 21st Arpil 2016
```

While I can deal with the council ref via /((DA|SA)\d{4}.\d+)/ there's no fixing the 13th month of the year, Arpil there :S

**Comment by henare** [comment]
I've just run this again and _all_ the addresses are appearing as ", TAS". This would mean none of them would geocode and therefore be useful in PlanningAlerts.

I think the work done in this scraper is a big improvement though so I'm going to merge this, disable auto-run on the scraper, and open an issue for the problem we're seeing.

**Pull request merged**
